### ISSUE TITLE
Unable to integrate with sbt-native-packager and aether 0.19

### ISSUE THREAD

**Issue by aloiscochard** [arktekk/sbt-aether-deploy#46]
This workaround:
https://stackoverflow.com/questions/23147029/using-sbt-aether-deploy-with-sbt-native-packager

Don't work anymore with latest 0.19, but works with 0.18.

I'm getting error like:
```
 mip-common-base/universal:packageZipTarball from mip-common-base/*:aetherArtifact ((com.swisscom.SwisscomPlugin.BIX) SwisscomPlugin.scala:117)

        at sbt.Init$class.Uninitialized(Settings.scala:270)
        at sbt.Def$.Uninitialized(Def.scala:10)
        at sbt.Init$class.delegate(Settings.scala:191)
        at sbt.Def$.delegate(Def.scala:10)
        at sbt.Init$class.compiled(Settings.scala:138)
        at sbt.Def$.compiled(Def.scala:10)
        at sbt.Init$class.make(Settings.scala:144)
        at sbt.Def$.make(Def.scala:
```

**Comment by aloiscochard** [comment]
Sorry, seems unrelated to version.. my bad.

Not sure what is going wrong though...
